<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html style="overflow: hidden; height: 100%;" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
	<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">	
	<title>TecTrace - Tracking</title>
	
	<!-- css site -->
	<link rel="stylesheet" href="<?php echo $this->cssUrl (); ?>stylesheet.css" type="text/css">
	<!-- css ui themes roller -->
	<link type="text/css" href="<?php echo $this->cssUrl (); ?>theme/default/jquery-ui.css" rel="Stylesheet" />	
	<!-- css motable -->
	<link rel="stylesheet" href="<?php echo $this->cssUrl (); ?>tables.css" type="text/css">
	
	<!-- google map key  -->
	<script src="http://maps.google.com/maps?file=api&amp;v=2.x&amp;key=<?php echo $this->googleMapsKey(); ?>"  type="text/javascript"></script>

	<script type="text/javascript" src="<?php echo $this->jsUrl ();?>gmap/gMapCore.js"></script>
	<script type="text/javascript" src="<?php echo $this->jsUrl();?>gmap/BDCCArrow.js"></script>
	<script type="text/javascript" src="<?php echo $this->jsUrl();?>gmap/runnerTrackingMapScripts.js"></script>
		
	<!-- framwework jquery  -->
	<script type="text/javascript" src="<?php echo $this->jsUrl (); ?>jquery/jquery.js"></script>
	<!--jquery ui -->
	<script type="text/javascript" src="<?php echo $this->jsUrl (); ?>jquery/jquery-ui-1.7.2.custom.min.js"></script>
	<!-- jquery layout -->
	<script type="text/javascript" src="<?php echo $this->jsUrl (); ?>jquery/jquery.layout.js"></script>
	<!-- table trie-groupement-filtre  -->
	<script type="text/javascript" src="<?php echo $this->jsUrl (); ?>tables/jquery.motable.js"></script>
	<!-- block ui -->
	<script type="text/javascript" src="<?php echo $this->jsUrl (); ?>jquery/jquery.blockUI.js"></script>

	<!-- common script -->
	<script type="text/javascript" src="<?php echo $this->jsUrl (); ?>json.js"></script>
	<script type="text/javascript" src="<?php echo $this->jsUrl (); ?>jquery/jquery.tipsy.js"></script>
	<script type="text/javascript" src="<?php echo $this->jsUrl (); ?>common.js"></script>


	<script type="text/javascript">	
    // variables booleens pour la correction des bug's de double appel de ready dans la 1er ouverture 
    //ou fermeture des slide     
    var menuCarsIsReady = false; 
    var menuDriverIsReady = false; 
    var menuLastLocalicalisation =false;
	var myLayout; // a var is required because this page utilizes: myLayout.allowOverflow() method
    
	// intervale de refrishisement 1 min
	var autoRefreshInterval = 15000;
	var autoRefreshTimer;  
	
    // true si les pois ont été dèja ajoutés à la carte 
	var _drawAllPois = false;
	// true si les pois ont affichés , false sinon
	var _showAllPois = false;
	// collection de pois
	var poisCollection = new Array; 
		
	//------------ gestion d'affichages des alertes dans  la carte ---------------------- */	
	var _alertsIdsDivsCollection = new Array; 
	var _showAlerts = false;	
		
	/** Ajouter un div alerte prèt du marqueur*/
	function addAlert(idCar,lat,lng,msg){	 
	   var idAlert = "alert_" + idCar;	
	   var idDiv = '#'+idAlert;		
	   $(map.getPane(G_MAP_FLOAT_SHADOW_PANE)).append("<div id="+idAlert+" style='position:absolute;width:100px;padding:3px;' class='hidden' align=left>"+msg+"</div>");
	   var alertInfo  = new Array(idDiv,lat,lng,idCar);	   
	   //_alertsIdsDivsCollection.push(alertInfo);	   
	   _alertsIdsDivsCollection["'" + idCar + "'" ] = alertInfo;
	}
	
	function showAlertOfCar(_idCar){
		try{
			var idCar = "'" + _idCar + "'";
		    if(!_showAlerts || _alertsIdsDivsCollection[idCar][0] == undefined )return;	   
	        var markerOffset = map.fromLatLngToDivPixel(new GLatLng(_alertsIdsDivsCollection[idCar][1],_alertsIdsDivsCollection[idCar][2]));
		    $(_alertsIdsDivsCollection[idCar][0]).show().css({top:markerOffset.y, left:markerOffset.x  });
		}
		catch(err){} 
	}
	
	function hideAlertOfCar(_idCar){
		try{
			var idCar = "'" + _idCar + "'";
	    	var ss =  _alertsIdsDivsCollection[idCar][0];
	    	if( ss != undefined )
	        $(_alertsIdsDivsCollection[idCar][0]).hide();		
	    }
		catch(err){}
		

	}
	
	/** repositionner toutes les alerts sur la carte ( utilisée après zoom de la carte ) */
	function redrawAllAlerts(){
	   if(!_showAlerts)return;
	   for( idCar in _alertsIdsDivsCollection){
	        try{	   
 			   var markerIsHidden = carsMarkersIsHidden["'"+_alertsIdsDivsCollection[idCar][3]+"'"];        
		       if( markerIsHidden == false){
		           var markerOffset = map.fromLatLngToDivPixel(new GLatLng(_alertsIdsDivsCollection[idCar][1],_alertsIdsDivsCollection[idCar][2]));
		           $(_alertsIdsDivsCollection[idCar][0]).show().css({top:markerOffset.y, left:markerOffset.x  });
		       }
		    }
		    catch(err){}
       }
	  
	}
	
	/** Afficher toutes les alerts dans la carte */
	function drawAllAlerts(){
	   
	   for( idCar in _alertsIdsDivsCollection){
	       try{
 			   var markerIsHidden = carsMarkersIsHidden["'"+_alertsIdsDivsCollection[idCar][3]+"'"];        
		       if( markerIsHidden == false)
		       {
		          var markerOffset = map.fromLatLngToDivPixel(new GLatLng(_alertsIdsDivsCollection[idCar][1],_alertsIdsDivsCollection[idCar][2]));
		          $(_alertsIdsDivsCollection[idCar][0]).show().css({top:markerOffset.y, left:markerOffset.x  });
		       }
		    }
		    catch(err){}
       }
       _showAlerts =true;

	}
	
	/** Masqué toutes les alertes*/
	function hideAllAlerts(){
	   for( idCar in _alertsIdsDivsCollection){
	      try{
 		  	 $(_alertsIdsDivsCollection[idCar][0]).hide();
 		  } catch(err){}
       }
        _showAlerts = false;   
	}	
	
	/** toogle des alertes ( pour afficher ou masquer les alertes )*/
	function toggleAlerts(){
	   if(_showAlerts)hideAllAlerts();
	   else drawAllAlerts();    
	}	
		/** Supprimmer tout les alertes */
	function removeAllAlerts(){
      for( idCar in _alertsIdsDivsCollection){
        try{
	       $(_alertsIdsDivsCollection[idCar][0]).remove();
	    } catch(err){}
	  }
	  _alertsIdsDivsCollection = null;	
	  _alertsIdsDivsCollection = new Array;    
	}
	//-------------------------------------------------------------//

	// Charger la carte ( données récupérées a traves la collection des localisations )
	function loadMap(){	   
	   map = createMap('map');
	   map.removeControl(new GMapTypeControl());  	   
	  <?php	
		if(isset($this->markersData) && count($this->markersData)>0)
		{
			$count =  count($this->markersData);
	   	  	for($i=0 ; $i<$count ; $i++){
				$idUnit = $this->markersData[$i]["idUnit"];	             
	             
				// si le véhciule possède  un boitier GPS
				if( $idUnit != "NOT_AVAILABLE")
				{	             
					$carName = $this->markersData[$i]["name"];
					$idCar = $this->markersData[$i]["idCar"];	             
					$idGroup = $this->markersData[$i]["idGroup"];	             
					$idDriver = $this->markersData[$i]["idDriver"];
					$lat = $this->markersData[$i]["lat"]; 	             
		            $lng = $this->markersData[$i]["lng"]; 	
					$markerColor = $this->markersData[$i]["markerColor"];	 
					$heading = $this->markersData[$i]["heading"];	 
					$toolTips = $this->markersData[$i]["toolTips"];	 
							
					if(!isset($heading))$heading=0;
					if(!isset($idDriver))$idDriver=0;
										
					echo 'addCarMarkerToMap('.$idUnit.','.$idCar.',"'.$carName.'",'.$idGroup.','.$idDriver. ',"'.$toolTips.'",' .$lat. ',' .$lng. ',"'.$markerColor.'",' .$heading. ');';
				
					$idAlert = $this->markersData[$i]["idAlert"];	 
					if(isset($idAlert) && $idAlert != Localisation::$_NO_ALERT){
						$dateLoc = $this->markersData[$i]["dateLoc"];						
						$msg = $this->alertOfId($idAlert,true,true);
						$id = $idCar.':'.$dateLoc;
						echo 'addAlert('.$idCar.','.$lat.','.$lng.',"'.$msg.'");';
				    }				 	

	           } 
	        }	 
		 }	
		 ?>  
		 GEvent.addListener(map,'zoomend',function(){redrawAllAlerts();}); 

	}	
	
	// mettre à jours les position des marqueyrs  dans  la carte	
	function refreshMap(){
		$('#divLoadMarkersPositions').show();
	    $.ajax({
		    type: "GET",
		    url: "<?php echo $this->url(array('controller'=>'map','action'=>'refresh-map') ); ?>",	 
		    contentType : "charset=ISO-8859-1",	   
		    success: function(msg){	                
		     	var markersData = $.parseJSON(msg);	  	
		  		mapClearOverlays(); // Effacer la carte	
		  		removeAllAlerts(); 	// Effacer les alertes  					
			   	if(markersData!=null && markersData.length>0)
			   	{	   	  	
					count =  markersData.length;
			   	  	for(i=0 ; i<count; i++){			   	  	   
			   	  	     var carName = markersData[i]["name"];		   	  	    
			             var idCar = markersData[i]["idCar"];	             
			             var idGroup = markersData[i]["idGroup"];	             
			             var idDriver = markersData[i]["idDriver"];
			             var idUnit = markersData[i]["idUnit"];	               
			             var toolTips = markersData[i]["toolTips"];	               
			             // si le véhciule possède  un boitier GPS
			             if( idUnit != "NOT_AVAILABLE")
			             {			             
			             	var markerColor = markersData[i]["markerColor"];	 			  			            
			             	var heading = markersData[i]["heading"];	 			  			            
				            var lat = markersData[i]["lat"]; 	             
				            var lng = markersData[i]["lng"]; 
				            if( idDriver == null) idDriver="";			             
							addCarMarkerToMap( idUnit, idCar,carName,idGroup,idDriver,toolTips,lat,lng, markerColor,heading);							
						    var idAlert = markersData[i]["idAlert"];						   
					        if(idAlert!=null && idAlert != <?php echo Localisation::$_NO_ALERT ?> ){						  					
						    	var msgAlert = markersData[i]["msgAlert"];
						    	addAlert(idCar,lat,lng,msgAlert);					
						    }
						             
	     		         }
			   	  	}
			   	 }
			   	 
			   	 // afficher les alerts si l'option d'affichage des alerts est activée
			   	 if(_showAlerts)drawAllAlerts();
			   	 // masquer tout les tooltips des marqueurs si ils été deja masqués
			   	 if(markersTooltipsIsHidden){ hideAllToolTips(); } 
			   	 
			   	 $('#divLoadMarkersPositions').hide();    	     	     		  	
	        }
	    }); 
	}
	
	$(document).ready(function () { 				    
	    $('#switcher').themeswitcher();
	    cssButton(); 	     
	    $("#mapMessage").hide();
	    
		myLayout = $('body').layout( {	
			   defaults: {
			            fxName:               "drop"
					,	fxSpeed_open:			750
					,	fxSpeed_close:			1500
					,	fxSettings_open:		{ easing: "easeInQuint" }
					,	fxSettings_close:		{ easing: "easeOutQuint" }			          			          	
			            
			   }			   	
			   ,east: {
		 		        size     : 360	
		 		      ,  resizable : false		
				      ,	onresize : '$("#accordion").accordion("resize");'   
		 	          ,	onopen   : '$("#accordion").accordion("resize");'   
		 	          ,	onclose  : '$("#accordion").accordion("resize");' 
		 	          ,	fxSpeed  : 'normal'		// slow, normal, fast, 1000, nnn
		 	          , fxSettings_open:		{ easing: "easeOutBounce" }		 	          
    
				}				
				,north: {
		 		        size      : 45	
		 		      ,	onresize  : '$("#accordion").accordion("resize");'   
		 	          ,	onopen    : '$("#accordion").accordion("resize");'   
		 	          ,	onclose   : '$("#accordion").accordion("resize");' 
		 	          , resizable : false   
			      	     
				}				    
		    	, south: {	 
		    	        size     : 140
		 	          , initClosed:   true
		 	          ,	onresize : '$("#accordion").accordion("resize");'   
		 	          ,	onopen   : '$("#accordion").accordion("resize");'   
		 	          ,	onclose  : '$("#accordion").accordion("resize");' 
		 	            
			    }    
		    }			   
		);
		
		$("#accordion").accordion({ 
               header: "h3",
               fillSpace:	true               
        });
        
        $("#_autoApdate").click(function () { 
		    if($(this).is('.ui-state-active'))	
		      autoRefreshTimer = setInterval( refreshMap ,  autoRefreshInterval ) ;
			 
			else 
			   clearInterval(autoRefreshTimer);    
		});
		
		$("#_refreshPositions").click(function () { 
		     refreshMap();
		});
		
		$("#_toogleFullScreen").click(function () { 
			if(!$(this).is('.ui-state-active'))
			{	
			  myLayout.open('north');	
			  myLayout.open('east');			 
			  //$.each('east,north'.split(','), function(){myLayout.show(this);});
			}  
			else 
			{	
			  myLayout.close('east');	 
			  myLayout.close('north');	 	
			  myLayout.close('south');	 	
			  $.each('north,south,east'.split(','), function(){myLayout.close(this);});
		    }
	   });	
		
       $("#_tooglePois").click(function ()  {   
	   	   if ($(this).is(':not(.ui-state-disabled)'))
	   	    togglePois();
	   });  
	   
	   $("#_toogleAlerts").click(function () {   
	   	   if ($(this).is(':not(.ui-state-disabled)'))
	   	   toggleAlerts();
	   	   
	   });
	   
	   $("#_toogleTooltips").click(function () {   
	   	   if(!$(this).is('.ui-state-active'))
	   	   		showAllToolTips();
	   	   else 
	   	   		hideAllToolTips();
	   	   
	   });
	   
	     
	   
  });
	
  </script>

</head>

<body onload="loadMap();" class="ui-widget-content" style="border: medium none; margin: 0pt; padding: 0pt; overflow: hidden; position: relative; height: 100%;">

<script type="text/javascript" src="<?php echo $this->jsUrl (); ?>jquery/themeswitchertool.js"> </script>
<div id="switcher" class="hidden"></div>
	
<!-- north -->      
<div  style="margin: 0pt; overflow: hidden; visibility: visible; display: block; position: absolute; z-index: 2;"
	pane="north"
	class="ui-widget-content ui-layout-north ui-layout-pane ui-layout-pane-north open">
	 <?php include_once ("default/header.phtml"); ?>
</div>
	
	
<!-- center -->
<div id='centerDiv' 
      style="margin: 0pt; visibility: visible; display: block; position: absolute; z-index: 2; height: 100%; width: 100%;" 
      pane="center" 
      class="ui-widget-content ui-layout-center ui-layout-pane ui-layout-pane-center open">


			<div id='mapControl' class="fg-toolbar ui-widget-header ui-corner-all ui-helper-clearfix" style="float:right ; position: absolute;right:0px;margin : 4px 10px 0px 0px; z-index: 100;opacity: 0.8;">
				 <div class="fg-buttonset ui-helper-clearfix">		
					  <a href="#" id='_toogleFullScreen' class="fg-button ui-state-default fg-button-icon-solo fg-button-toggleable  ui-corner-all" title="Plein Ecran"><span class="ui-icon ui-icon-arrow-4-diag"></span>Plein Ecran</a>
					  <a href="#" id='_refreshPositions' class="fg-button ui-state-default fg-button-icon-solo ui-corner-all" title="Rafraîchir la carte"><span class="ui-icon ui-icon-refresh"></span>Rafraîchir la carte</a>
			
				 </div>
				 
				 <div class="fg-buttonset fg-buttonset-multi">		
				 	  <a href="#" id='_autoApdate' class="fg-button ui-state-default fg-button-icon-solo fg-button-toggleable ui-corner-left" title="Rafraîchsement automatique"><span class="ui-icon ui-icon-arrowrefresh-1-w"></span>Auto rafraîchsement</a>
					  <a href="#" id='_toogleTooltips' class=" fg-button ui-state-default fg-button-icon-solo  fg-button-toggleable" title="Afficher/Masquer les noms des véhicules sur la carte"><span class="ui-icon ui-icon-comment"></span>Afficher/Masquer les noms des véhicules</a>
					  <a href="#" id='_tooglePois' class=" fg-button ui-state-default fg-button-icon-solo  fg-button-toggleable" title="Afficher/Masquer les poi's sur la carte"><span class="ui-icon ui-icon-pin-s"></span>Afficher/Masquer les poi's</a>
					  <a href="#" id='_toogleAlerts' class="fg-button ui-state-default fg-button-icon-solo  fg-button-toggleable ui-corner-right" title="Afficher/Masquer les alèrtes sur la carte"><span class="ui-icon ui-icon-alert"></span>Afficher/Masquer les alertes</a>
				</div>
				
				<div class="fg-buttonset fg-buttonset-single ui-helper-clearfix">
					  <button onclick="map.setMapType(G_NORMAL_MAP);" class="fg-button ui-state-default ui-state-active ui-priority-primary ui-corner-left">Plan</button>
					  <button onclick="map.setMapType(G_SATELLITE_MAP);" class="fg-button ui-state-default ui-priority-primary ">Satellite</button>
					  <button onclick="map.setMapType(G_HYBRID_MAP);" class="fg-button ui-state-default ui-priority-primary ">Mixte</button>
					  <button onclick="map.setMapType(G_MAPMAKER_NORMAL_MAP);" class="fg-button ui-state-default ui-priority-primary ui-corner-right">Relief</button>
				 </div>    
				    	    
				 <div class="fg-buttonset ui-helper-clearfix">		  	   
				      <div id="divLoadMarkersPositions" style="display:none;position: absolute;float:right; right : 15px; margin-right:0px;margin-top: 7px;" align="right">  <img src="<?php echo $this->imgUrl()."wait.gif"; ?>" > </div>
				 </div>	
				 				    
			</div>
			
			<div id='mapMessage' class="ui-widget-header ui-corner-all ui-helper-clearfix" style="position: absolute; float:right;right:0px;margin :50px 10px 0px 0px; z-index: 100;opacity: 0.8;width: 180px;"></div>	        
				
			<!-- <div align="center" id="map" style="width:100%;height:100%; position:relative;overflow-y: hidden;" ></div>-->
			<div align="center" id="map" style="overflow: hidden; position: relative; width: 100%; background-color: rgb(229, 227, 223); height: 100%;" ></div>
	
	



</div>
	
<!-- east -->
<div style="margin: 0pt; overflow: hidden; visibility: visible; display: block; position: absolute; z-index: 2; padding: 5px;" 
     pane="east" 
     class="ui-widget-content ui-layout-east ui-layout-pane ui-layout-pane-east open">


	<div id="accordion" class="accordion" >
		<h3 style="font: 0.9em verdana, arial, sans-serif;"> <a href="#" class="none">MES VEHICULES</a></h3>
		<div> <?php echo $this->action('menu-cars','map'); ?></div>
		
		<h3 style="font: 0.9em verdana, arial, sans-serif;" > <a href="#" class="none">MES CONDUCTEURS</a></h3>
		<div > <?php echo $this->action ( 'menu-drivers', 'map');?></div>
		
		<h3 style="font: 0.9em verdana, arial, sans-serif;"><a href="#" class="none">LISTE DE SUIVI</a></h3>
		<div> <?php echo $this->action ('menu-tracking','map'); ?></div>

	</div>
	
	
</div>	
	
<!---south -->
<div  style="margin: 0pt; visibility: visible; display: block; position: absolute; z-index: 2;overflow: hidden;" 
      pane="south" 
      class="ui-widget-content ui-layout-south ui-layout-pane ui-layout-pane-south open">

    <div id='infosContainer'> </div>  
 
     
</div>

</body>
</html>


<?php
//----------------------- Points d'intèret ------------------------//

if(isset($this->poiCollection) && $this->poiCollection->count() >0)
{
?>
	
<script>

// ajouter un poi pour affichage format marqueur
function addPoiMarker(name,description,centerpoint,iconUrl){ 
    var icon0 = new GIcon(); 
	icon0.image = 'http://127.0.0.1/Tec_Trace/'+iconUrl;
    icon0.iconSize = new GSize(24, 24);
	icon0.iconAnchor = new GPoint(9, 34);
	icon0.infoWindowAnchor = new GPoint(9, 2);
	icon0.infoShadowAnchor = new GPoint(18, 25);	
	var marker = new GMarker(centerpoint,icon0);	
	poisCollection.push(marker); 
    
    GEvent.addListener(marker,"mouseover", function() { 
	     $("#mapMessage").html('<table width="100%" ><tr><td>Poi :</td><td style="text-align:left;">'+name+'</td></tr></table>');
	     $("#mapMessage").fadeIn('slow');
	}); 
	    
	GEvent.addListener(marker,"mouseout", function() {     
	     $("#mapMessage").fadeOut('slow');
	}); 
}	

// ajouter tout les pois à la carte
function drawAllPois(){
  for(var i=0;i<poisCollection.length;i++)map.addOverlay(poisCollection[i]);
  _drawAllPois = true;
  _showAllPois = true;
}

// afficher tout le pois
function showAllPois(){
  for(var i=0;i<poisCollection.length;i++)poisCollection[i].show();
  _showAllPois =true;
}

// masquer tout les pois
function hideAllPois(){
  for(var i=0;i<poisCollection.length;i++)poisCollection[i].hide();
  _showAllPois =false;
}

// afficher ou masquer tout les pois 
function togglePois(){
  if(!_drawAllPois){
     drawAllPois();
     return;
  }
  if(_showAllPois)hideAllPois();
  else showAllPois();
}

</script>
	<?php	
	$count = $this->poiCollection->count();	
	$picturesDirConfig = Zend_Registry::get('picturesDirConfig');	
	$poimarkersDir  = $picturesDirConfig->pictures->params->poimarkers; 
   	for($i=0; $i< $count ; $i++){
		$poi = $this->poiCollection->getPoi($i);		
		$idPoi = $poi->getId();	
        $name =  $this->escape($poi->getName());       
        $Description =  $this->escape($poi->getName());       
        $imgMarkerPath = $poimarkersDir. $this->imgPathOfMarker( $poi->getIdMarker() );    
 		echo "<script>var point = new GLatLng(" . $poi->getLatitude()  . "," . $poi->getLongitude() . ");</script>";	    
		echo "<script>addPoiMarker('".$name."','".$Description."',point, '".$imgMarkerPath."' );</script>";	    		

	}
}	
?>



